[theme]
# Primary accent color for interactive elements.
primaryColor = "#b7410e"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#c5bebe"

# Color used for almost all text.
textColor = "#00000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"